apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  type: NodePort
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 8080        # El puerto que escucha tu aplicación dentro del contenedor
      targetPort: 8080  # Igual al anterior
      nodePort: 30823   # Puedes dejar que lo asigne automáticamente si no lo pones
